### ISSUE TITLE
Best Region Issue

### ISSUE THREAD

**Issue by cloudhu** [cloudhu/Strange-MMO-VR#4]
Here is the problem:I unlocked the China Server for Chinese players to get a good game experience,but I also don't wanna lose other region's players.Is there a  solution for that?
And here is my code for enable China Server:
1. Change NameServerHost to "ns-cn.exitgames.com" in :Assets\Photon Unity Networking\Plugins\PhotonNetwork\NetworkingPeer.cs,is this means to lose other region?
2. I added cn to enum CloudRegionCode and CloudRegionFlag in the path：Assets\Photon Unity Networking\Plugins\PhotonNetwork\Enums.cs ,this is fine for connect to China Server.
3. As I don't wanna lose other region I changed Hostings to Best Region in the PhotonServerSettings.
That's it.If you're not in China you can test your region connect for me,that's would be very kind of you!And I'm waiting for a solution for my problem,thanks a lot.

And the China Server did not support PUNVoice yet? I got this :PUNVoice: OperationResponse 230: ReturnCode: 32767 (ApplicationNotFound). Parameters: {} Server: NameServer Address: ns-cn.exitgames.com:5058 error when I try to reach PUNVoice on China Server!

**Comment by jiezhixing008** [comment]
这是啥啊，，，都是中国人，用中文被。。。

**Comment by cloudhu** [comment]
这个问题其实没有太好的解决方案,目前的办法是中国区使用中国的服务器,国外使用欧美的服务器.也就是要打包两个不同的客户端.
